"""fecha de entrega en evaluaciones

Revision ID: 75c80e3551a3
Revises: d8745698c4e0
Create Date: 2024-10-11 18:55:56.569448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75c80e3551a3'
down_revision = 'd8745698c4e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asignaciones', schema=None) as batch_op:
        batch_op.alter_column('rol_asignado',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'estudiante'"))
        batch_op.drop_constraint('asignaciones_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('asignaciones_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'cursos', ['curso_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('evaluaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_entrega', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluaciones', schema=None) as batch_op:
        batch_op.drop_column('fecha_entrega')

    with op.batch_alter_table('asignaciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('asignaciones_ibfk_2', 'usuarios', ['usuario_id'], ['id'])
        batch_op.create_foreign_key('asignaciones_ibfk_1', 'cursos', ['curso_id'], ['id'])
        batch_op.alter_column('rol_asignado',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'estudiante'"))

    # ### end Alembic commands ###
